version: "2"
services:
  client:
    build:
      dockerfile: Dockerfile
      context: "./client"
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./client:/client
      - /client/node_modules
    links:
      - api
    networks:
      - customerfeedback
  api:
    build:
      dockerfile: Dockerfile
      context: "./api"
    environment:
      - DB_HOST=mongodb
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - ./api:/api
      - /api/node_modules
    depends_on:
      - mongodb
    networks:
      - customerfeedback
  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    volumes:
      - ./data-node:/data/db
    ports:
      - 27017:27017
    command: mongod --noauth --smallfiles
    networks:
      - customerfeedback
networks:
  customerfeedback:
    driver: bridge